import { Router, type IRouter } from "express";
import healthRouter from "./health";
import fsRouter from "./ide/fs";
import runRouter from "./ide/run";
import aiRouter from "./ide/ai";
import contextRouter from "./ide/context";
import agentRouter from "./ide/agent";
import memoryRouter from "./ide/memory";
import authRouter from "./platform/auth";
import projectsRouter from "./platform/projects";
import deployRouter from "./platform/deploy";
import devopsRouter from "./platform/devops";
import containersRouter from "./platform/containers";
import nodesRouter from "./platform/nodes";
import billingRouter from "./platform/billing";
import teamsRouter from "./platform/teams";
import pluginsRouter from "./platform/plugins";
import marketplaceRouter from "./platform/marketplace";
import searchRouter from "./platform/search";

const router: IRouter = Router();

router.use(healthRouter);
router.use(fsRouter);
router.use(runRouter);
router.use(aiRouter);
router.use(contextRouter);
router.use(agentRouter);
router.use(memoryRouter);
router.use(authRouter);
router.use(projectsRouter);
router.use(deployRouter);
router.use(devopsRouter);
router.use(containersRouter);
router.use(nodesRouter);
router.use(billingRouter);
router.use(teamsRouter);
router.use(pluginsRouter);
router.use(marketplaceRouter);
router.use(searchRouter);

export default router;
