import { Router, type IRouter } from "express";
import healthRouter from "./health";
import fsRouter from "./ide/fs";
import runRouter from "./ide/run";
import aiRouter from "./ide/ai";
import contextRouter from "./ide/context";
import agentRouter from "./ide/agent";
import memoryRouter from "./ide/memory";
import authRouter from "./platform/auth";
import projectsRouter from "./platform/projects";
import deployRouter from "./platform/deploy";
import devopsRouter from "./platform/devops";
import containersRouter from "./platform/containers";
import nodesRouter from "./platform/nodes";
import billingRouter from "./platform/billing";
import teamsRouter from "./platform/teams";
import pluginsRouter from "./platform/plugins";
import marketplaceRouter from "./platform/marketplace";
import searchRouter from "./platform/search";
import orchestratorRouter from "./platform/orchestrator";
import globalSchedulerRouter from "./platform/globalscheduler";
import functionsRouter from "./platform/functions";
import healingRouter from "./platform/healing";
import routingRouter from "./platform/routing";
import observabilityRouter from "./platform/observability";
import infragenRouter from "./platform/infragen";
import environmentsRouter from "./platform/environments";
import strategiesRouter from "./platform/strategies";
import secretsRouter from "./platform/secrets";
import pipelinesRouter from "./platform/pipelines";
import releaseAiRouter from "./platform/release-ai";
import trialRouter from "./platform/trial";
import referralRouter from "./platform/referral";
import streakRouter from "./platform/streak";
import achievementsRouter from "./platform/achievements";
import marketplaceEngineRouter from "./platform/marketplace-engine";
import templatesRouter from "./platform/templates";
import creatorRouter from "./platform/creator";
import fraudRouter from "./platform/fraud";
import adminRouter from "./admin/index";

const router: IRouter = Router();

router.use(healthRouter);
router.use(fsRouter);
router.use(runRouter);
router.use(aiRouter);
router.use(contextRouter);
router.use(agentRouter);
router.use(memoryRouter);
router.use(authRouter);
router.use(projectsRouter);
router.use(deployRouter);
router.use(devopsRouter);
router.use(containersRouter);
router.use(nodesRouter);
router.use(billingRouter);
router.use(teamsRouter);
router.use(pluginsRouter);
router.use(marketplaceRouter);
router.use(searchRouter);
router.use(orchestratorRouter);
router.use(globalSchedulerRouter);
router.use(functionsRouter);
router.use(healingRouter);
router.use(routingRouter);
router.use(observabilityRouter);
router.use(infragenRouter);
router.use(releaseAiRouter);
router.use(trialRouter);
router.use(referralRouter);
router.use(streakRouter);
router.use(achievementsRouter);
router.use(marketplaceEngineRouter);
router.use(templatesRouter);
router.use(creatorRouter);
router.use(fraudRouter);
router.use(environmentsRouter);
router.use(strategiesRouter);
router.use(secretsRouter);
router.use(pipelinesRouter);
router.use(adminRouter);

export default router;
